---
- type: job
  id: Knight
  name: Knight
  description: Protect The Monarch
  playTimeTracker: JobKnight
  startingGear: KnightGear
  icon: JobIconKnight
  goobcoins: 30
  access:
  - Monarchy
  - Maintenance
  - Barracks
- type: startingGear
  id: KnightGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    head: CardHelmet
    ears: ClothingHeadsetMonarchy
    outerClothing: CardArmour
    gloves: ClothingHandsGlovesColorLightBrown
    back: ClothingBackpackSatchelSalvage
    shoes: ClothingShoesBootsCowboyBrown
    suitstorage: CardSword
    id: KnightPDA
  storage:
    back:
    - MaterialCardboard
